### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by ccomerImmerge** [colinbjohnson/aws-missing-tools#106]
Hi,

I may be missing something but I can't seem to find the file for the cli automated backup tools (using this command: wget https://raw.githubusercontent.com/colinbjohnson/aws-missing-tools/master/ec2-automate-backup/ec2-automate-backup-awscli.sh). Has the file been moved?

**Comment by colinbjohnson** [comment]
Hi @ccomerImmerge - you are correct - the file has been moved to this location: https://raw.githubusercontent.com/colinbjohnson/aws-missing-tools/master/ec2-automate-backup/ec2-automate-backup.sh.

**Comment by ccomerImmerge** [comment]
Just to be clear, is that the file that uses the AWS CLI? In the readme the file that uses the AWS CLI is named ec2-automate-backup-awscli.sh.
