### ISSUE TITLE
Transfer Custom tags to backup

### ISSUE THREAD

**Issue by Gerben-W** [colinbjohnson/aws-missing-tools#114]
I love the script, but I still have a question.
We use custom tags for different CostLocations, now we would like to transfer the custom values for a "Billing" and a "CostLocation" tag to the snapshot.
Is this possible?

**Comment by toby1kenobi** [comment]
Yes, this would be very useful to us too

**Comment by toby1kenobi** [comment]
Ok, this is what I did (possibly inelegant/wrong, I'm no shell expert!) - I wanted to copy across our tags 'client' and 'project':

```
create_EBS_Snapshot_Tags() {
  #snapshot tags holds all tags that need to be applied to a given snapshot - by aggregating tags we ensure that ec2-create-tags is called only onece
  snapshot_tags=""

  # Apply client and project tags to snapshot
  ec2_tag_list=$(aws ec2 describe-tags --filters "Name=resource-id,Values=${ebs_selected}" --query 'Tags[?Key==`project` || Key==`client`].[Key,Value]' --output text 2>&1)

  if [ !"$ec2_tag_list" ]; then
    IFS=$'\n' read -d '' -r -a lines <<< "$ec2_tag_list"

    for i in "${lines[@]}"; do
      parts=($i)
      snapshot_tags="$snapshot_tags Key=${parts[0]},Value=${parts[1]}"
    done
  fi

```

This is in an older version of the automate backup script, hopefully gives the idea though.

**Comment by toby1kenobi** [comment]
FYI, I did a better version of this, which is in a pull request https://github.com/colinbjohnson/aws-missing-tools/pull/123

**Comment by Gerben-W** [comment]
@toby1kenobi Thanks for the change. It works like a charm.
Both the Tags are working if I add them with "-d Billing,CostLocation" to the command.

Thanx again
