### ISSUE TITLE
backing up via tags seems to fail

### ISSUE THREAD

**Issue by joech4n** [colinbjohnson/aws-missing-tools#84]
Backing up by selecting volume seems to work:

    $ ec2-automate-backup-awscli.sh -r us-west-2 -k 30 -v vol-abcd5678
    Snapshots taken by ec2-automate-backup-awscli.sh will be eligible for purging after the following date (the purge after date given in seconds from epoch): 1424711645.
    Tagging Snapshot snap-abcd5678 with the following Tags:  Key=PurgeAfterFE,Value=1424711645 Key=PurgeAllow,Value=true

Backing up by selecting tags seems to fail (no output or snap created):

    $ ec2-automate-backup-awscli.sh -r us-west-2 -k 30 -s tag -t "Backup-Daily=true" -h
    Snapshots taken by ec2-automate-backup-awscli.sh will be eligible for purging after the following date (the purge after date given in seconds from epoch): 1424711461.

I think I have the volume tagged correctly:

    $ aws ec2 describe-volumes --volume-ids vol-abcd5678
    {
        "Volumes": [
            {
                "AvailabilityZone": "us-west-2a",
                "Attachments": [
                    {
                        "AttachTime": "2012-12-01T01:20:58.000Z",
                        "InstanceId": "i-abcd5678",
                        "VolumeId": "vol-abcd5678",
                        "State": "attached",
                        "DeleteOnTermination": true,
                        "Device": "/dev/sda1"
                    }
                ],
                "Tags": [
                    {
                        "Value": "true",
                        "Key": "Backup-Daily"
                    },
                    {
                        "Value": "a.iam.vpc",
                        "Key": "Name"
                    }
                ],
                "Encrypted": false,
                "VolumeType": "standard",
                "VolumeId": "vol-abcd5678",
                "State": "in-use",
                "SnapshotId": "snap-abcd5678",
                "CreateTime": "2012-12-01T01:20:58.000Z",
                "Size": 8
            }
        ]
    }

**Comment by kkumler** [comment]
@joech4n The documentation is slightly off on that. Try it with `-t "Backup-Daily,Values=true"`

**Comment by joech4n** [comment]
Thanks for checking this out! I'm still seeing the same behavior with your suggested tag:

    > aws ec2 describe-volumes --volume-ids vol-4d98fe5c
    {
        "Volumes": [
            {
                "AvailabilityZone": "us-west-2a",
                "Attachments": [
                    {
                        "AttachTime": "2015-01-24T16:09:46.000Z",
                        "InstanceId": "i-ee7052e4",
                        "VolumeId": "vol-4d98fe5c",
                        "State": "attached",
                        "DeleteOnTermination": false,
                        "Device": "xvdb"
                    }
                ],
                "Tags": [
                    {
                        "Value": "cp",
                        "Key": "Name"
                    },
                    {
                        "Value": "true",
                        "Key": "Backup-Daily"
                    }
                ],
                "Encrypted": false,
                "VolumeType": "gp2",
                "VolumeId": "vol-4d98fe5c",
                "State": "in-use",
                "Iops": 1500,
                "SnapshotId": null,
                "CreateTime": "2015-01-24T16:09:46.731Z",
                "Size": 500
            }
        ]
    }
    
    > ec2-automate-backup-awscli.sh -r us-west-2 -k 30 -s tag -t "Backup-Daily=true,Values=true" -h
    Snapshots taken by ec2-automate-backup-awscli.sh will be eligible for purging after the following date (the purge after date given in seconds from epoch): 1427296520.

**Comment by kkumler** [comment]
It's just dropping the tag field through to the aws call, which has the format `--filters Name=tag:<tagname>,Values=<acceptable values>`
so try:
`ec2-automate-backup-awscli.sh -r us-west-2 -k 30 -s tag -t "Backup-Daily,Values=true" -h`

**Comment by joech4n** [comment]
That worked! Thank you! :clap:
