### ISSUE TITLE
Can't make an EC2 Backup

### ISSUE THREAD

**Issue by BrunoSette** [colinbjohnson/aws-missing-tools#85]
I got the error message: 

root ~ $ ./ec2-automate-backup.sh -r sa-east-1b -v vol-b4ddceb2

An error occurred when running ec2-describe-volumes. The error returned is below:
Unknown problem connecting to host: 'https://ec2.sa-east-1b.amazonaws.com'
Unable to execute HTTP request: ec2.sa-east-1b.amazonaws.com

Help Please?

**Comment by colinbjohnson** [comment]
Hi @BrunoSette - did you get everything figured out? Curious as to what was wrong.
