### ISSUE TITLE
Could not connect to "https://ec2.ap-southeast-1a.amazonaws.com/"

### ISSUE THREAD

**Issue by tarunguptapec** [colinbjohnson/aws-missing-tools#97]
While running the below script i get the following error

sudo ./ec2-automate-backup-awscli.sh -v "vol-31627b24" -r "ap-southeast-1a"

Could not connect to the endpoint URL: "https://ec2.ap-southeast-1a.amazonaws.com/"
An error occurred when running ec2-describe-volumes. The error returned is below:

I get the same error while using ec2-automate-backup.sh

Any Idea?

**Comment by pwakeford** [comment]
Your region should be ap-southeast-1 not ap-southeast-1a

1a is an AZ not a region. 


Paul

**Comment by tarunguptapec** [comment]
Silly me. Thanks Paul.
